version: '3.8'

services:
  lrcget:
    build: .
    volumes:
      - lrcget_data:/data
      - /home/diego/Code/Ninja/musicdock/stack/media/music:/music  # Mount your music library as read-only
    environment:
      - LRCGET_DATABASE_PATH=/data/lrcget.db
      - LRCGET_LRCLIB_DATABASE_PATH=/data/lrclib.db  # Optional
      - LRCGET_REDIS_URL=redis://redis:6379  # Optional Redis cache
      - RUST_LOG=info
    depends_on:
      - redis  # Optional

  redis:  # Optional caching service
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  lrcget_data:
  redis_data: